name: keyboard_attachable_fork
description: A Flutter package to build widgets that can be attached to the soft keyboard.
version: 0.0.1
homepage: https://github.com/drogel/keyboard_attachable

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility_fork: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
